# Generated by Django 3.2 on 2024-01-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(blank=True, default=False, verbose_name='В избранном'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(blank=True, default=False, verbose_name='В корзине'),
        ),
    ]
