# Generated by Django 3.2 on 2024-01-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240122_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='recipe/images/', verbose_name='Фото'),
        ),
    ]
