# Generated by Django 3.2 on 2024-01-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipess', to='recipes.recipe', verbose_name='Рецепт в корзине'),
        ),
    ]
