# Generated by Django 3.2 on 2024-01-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
